# Generated by Django 3.0.3 on 2020-02-11 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phantom', '0002_auto_20200211_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
