# Generated by Django 3.0.3 on 2020-02-11 06:11

from django.db import migrations, models
import django.db.models.deletion
import phantom.models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom', '0003_auto_20200211_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=phantom.models.upload_image_path)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='phantom.Advertisement')),
            ],
        ),
    ]
