# Generated by Django 3.0.3 on 2020-02-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phantom', '0004_advertisementimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
